d=dir('../ESC-50');%directory dove avete salvato il dataset
d(ismember( {d.name}, {'.', '..'})) = [];  %remove . and ..
for classe = 1:50
    nm = strcat(d(classe).name);
    folder = fullfile("../ESC-50/" + nm);
    ADS = audioDatastore(folder);
    numFilesInDataset = numel(ADS.Files);
    aug = audioDataAugmenter(...
            "NumAugmentations",10, ...
            ...
            "TimeStretchProbability",0.8, ...
            "SpeedupFactorRange", [1.3,1.4], ...
            ...
            "PitchShiftProbability",0.1, ...
            ...
            "VolumeControlProbability",0.8, ...
            "VolumeGainRange",[-5,5], ...
            ...
            "AddNoiseProbability",0.05, ...
            ...
            "TimeShiftProbability",0.8, ...
            "TimeShiftRange", [-1e-2,1e-2]);

    while hasdata(ADS)
        [audioIn,info] = read(ADS);

        data = augment(aug,audioIn,info.SampleRate);

        [~,fn] = fileparts(info.FileName);
        for i = 1:size(data,1)
            augmentedAudio = data.Audio{i};

            % If augmentation caused an audio signal to have values outside of -1 and 1, 
            % normalize the audio signal to avoid clipping when writing.
            if max(abs(augmentedAudio),[],'all')>1
                augmentedAudio = augmentedAudio/max(abs(augmentedAudio),[],'all');
            end
            name = strsplit(nm," - ");
            name = name{2};
            filename = sprintf("C:\\Users\\vincm\\Desktop\\Vincenzo\\Universita\\3.2\\AI\\Progetto\\AUG2\\%s_aug%d.wav",name,i);
            audiowrite(filename,augmentedAudio,info.SampleRate)
        end
    end
end